# site properties and page defaults
title: 时空大数据智能与计算实验室
title_en: Spatiotemporal Big Data Intelligence and Computing Lab
subtitle: 哈尔滨工业大学（深圳）计算机科学与技术学院
subtitle_en: School of Computer Science and Technology, HIT Shenzhen
description: 实验室研究方向为数据挖掘、机器学习、时空大数据分析与智能，智慧城市等。
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: contact@your-lab.com
  github: MiSevenJoy

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: news

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff

# configure jekyll spaceship
jekyll-spaceship:
  mathjax-processor:
    src:
      - https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js
