name: on-pull-request
run-name: On pull request activity

on:
  # run on any pull request activity
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  actions: read
  contents: write
  pull-requests: write

jobs:
  build-preview:
    if: ${{ !cancelled() && !failure() }}
    uses: ./.github/workflows/build-preview.yaml
